<a href="https://colab.research.google.com/github/Udaykiran444/data-science-project-women-clothing-review-prediction-/blob/main/women_cloth_review_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Women Cloth Reviews Predictions With Multinomial Naive Bayes**

**Import library**

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib as mtb

In [4]:
import seaborn as sns

**Import Dataset**

In [5]:
df=pd.read_csv("/content/Womens Clothing E-Commerce Reviews.csv")

**Describe Data**

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


**Data Visualization**

In [7]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [8]:
df.tail()

Unnamed: 0  Clothing ID  Age  \
23481       23481         1104   34   
23482       23482          862   48   
23483       23483         1104   31   
23484       23484         1084   28   
23485       23485         1104   52   

                                                   Title  \
23481                     Great dress for many occasions   
23482                         Wish it was made of cotton   
23483                              Cute, but see through   
23484  Very cute dress, perfect for summer parties an...   
23485                    Please make more like this one!   

                                             Review Text  Rating  \
23481  I was very happy to snag this dress at such a ...       5   
23482  It reminds me of maternity clothes. soft, stre...       3   
23483  This fit well, but the top was very see throug...       3   
23484  I bought this dress for a wedding i have this ...       3   
23485  This dress in a lovely platinum is feminine an...       5   

       Recommended IND  Positive Feedback Count   Division Name  \
23481                1                        0  General Petite   
23482                1                        0  General Petite   
23483                0                        1  General Petite   
23484                1                        2         General   
23485                1                       22  General Petite   

      Department Name Class Name  
23481         Dresses    Dresses  
23482            Tops      Knits  
23483         Dresses    Dresses  
23484         Dresses    Dresses  
23485         Dresses    Dresses

In [9]:
df.shape

(23486, 11)

**Data Preprocessing**

In [10]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [11]:
df[df['Review Text']==""]=np.NaN

In [12]:
df['Review Text'].fillna("No Review",inplace=True)

In [13]:
df[df['Recommended IND']==""]=np.NaN

In [14]:
df['Recommended IND'].fillna("No Recomended IND",inplace=True)

In [15]:
df[df['Positive Feedback Count']==""]=np.NaN

In [16]:
df['Positive Feedback Count'].fillna("No Positive Feedback Count",inplace=True)

In [17]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [18]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

In [19]:
df['Rating']

0        4
1        5
2        3
3        5
4        5
        ..
23481    5
23482    3
23483    3
23484    3
23485    5
Name: Rating, Length: 23486, dtype: int64

In [20]:
# prompt: delete the last row

df = df.drop(df.index[-1])


**Define Target (y) and Feature (x)**

In [21]:
df.columns


Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [22]:
x= df['Review Text']

In [23]:
y=df['Rating']

**Train Test Split**

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y ,train_size = 0.7)

In [26]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16439,), (7046,), (16439,), (7046,))

**Modeling**

In [38]:
# prompt: next step

from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

model = Pipeline([
    ("vectorizer", TfidfVectorizer()),
    ("classifier", MultinomialNB()),
])

model.fit(x_train, y_train)


Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('classifier', MultinomialNB())])

In [41]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

**Get model prediction**

In [48]:
y_pred = model.predict(x_test)

In [46]:
y_pred.shape

(7046,)

In [49]:
y_pred

array([5, 5, 5, ..., 5, 5, 5])

**Get Model Evaluation**

In [50]:
from sklearn.metrics import confusion_matrix, classification_report

In [51]:
# **Evaluate Model**
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np # Import numpy

# Check and convert y_test to a NumPy array if it isn't already
if not isinstance(y_test, np.ndarray):
    y_test = np.array(y_test)
# Ensure both arrays have the same data type (e.g., integer)
if y.dtype != x.dtype:
  y = y.astype(x.dtype)

In [52]:
# **Evaluate Model**
# Accuracy
# Ensure y_test is defined and is a numpy array with the correct data type
y_test = np.array(y_test)  # Replace y_test with your actual test data
y_test = y_test.astype(y_pred.dtype) # Ensure y_test and y_pred have the same data type

acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")

# Confusion Matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cf_matrix}")

# Classification Report
clas_report = classification_report(y_test, y_pred)
print(f"Classification Report:\n{clas_report}")


Accuracy: 0.5617371558330968
Confusion Matrix:
[[   0    0    3    5  236]
 [   0    0    5    6  466]
 [   0    0    4    2  854]
 [   0    0    0    2 1510]
 [   0    0    0    1 3952]]
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       244
           2       0.00      0.00      0.00       477
           3       0.33      0.00      0.01       860
           4       0.12      0.00      0.00      1512
           5       0.56      1.00      0.72      3953

    accuracy                           0.56      7046
   macro avg       0.20      0.20      0.15      7046
weighted avg       0.38      0.56      0.41      7046



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
